### PR TITLE
fixed navbar and added footer to the website

### PR DESCRIPTION
**Pull request by GAGANRAGHAV**
screenshot --

image

added the footer 

image

completed two of the issues in this pr only

### CODE REVIEW

**Comment by VishalIITP** [comment]
The footer is good but the "Here's how it works over the 2 weeks." got distorted in this pr. Try to keep it as before and if you have some doubt let me know and keep the timetable, Leaderboard pages blank as of now or add some dummy text only.
image

**Comment by GAGANRAGHAV** [comment]
sir made the necessary changes

**Comment by VishalIITP** [comment]
Nav Links are not working properly.
1. Not able to got to dashboard after timetable.
2. Page is reloading on clicking Leaderboard.

**Comment by GAGANRAGHAV** [comment]
Sir there is no. Leaderboard and dashboard pages ....that why it's not going anywhere

**Comment by GAGANRAGHAV** [comment]
Sir should i create new pages for leaderboard and dashboard and restructure the navlinks

**Comment by GAGANRAGHAV** [comment]
sir  i have made some changes in the navbar ...and please tell should i raise other issues to add leaderboard and dashboard ...i want to work on this project to improve my react and prepare for gsoc

**Comment by VishalIITP** [comment]
> Sir should i create new pages for leaderboard and dashboard and restructure the navlinks

yes make blank pages containing texts leaderboard and dasboard

**Comment by VishalIITP** [comment]
> sir i have made some changes in the navbar ...and please tell should i raise other issues to add leaderboard and dashboard ...i want to work on this project to improve my react and prepare for gsoc

Merging your PR after this one, you can proceed by creating issue I will assign them to you.

**Pull request merged**
